# Generated by Django 4.0.1 on 2022-02-09 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('avatar', models.ImageField(blank=True, upload_to='author')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('script', models.CharField(blank=True, max_length=200)),
                ('category_image', models.ImageField(blank=True, upload_to='dashboard')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
                ('image_square', models.ImageField(blank=True, null=True, upload_to='news square')),
                ('article', models.TextField()),
                ('add_time', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('cmt_count', models.PositiveIntegerField(default=4)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_news', to='homepage.author')),
                ('main_category', models.ForeignKey(default='Crypto', on_delete=django.db.models.deletion.CASCADE, related_name='category_news', to='homepage.category')),
                ('tag', models.ManyToManyField(blank=True, related_name='newsTag', to='homepage.Tag')),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-views', '-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('cmt_time', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_ava')),
                ('news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='post_comments', to='homepage.news')),
            ],
        ),
    ]
