# Generated by Django 4.0.1 on 2022-02-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cmt_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
