# Generated by Django 4.0.1 on 2022-02-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_news_cmt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cmt_count',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=61),
        ),
    ]
