# Generated by Django 4.0.1 on 2022-02-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_news_cmt_count_alter_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='cmt_count',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=51),
        ),
    ]
